name: Build and Push Docker Image (multiple architectures)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (displayed in the docker image tag).'
        required: true
      update-latest:
        description: 'Should this image overwrite the `latest` tag?'
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set image tags
      run: |
        if [[ ${{ inputs.update-latest }} == 'true' ]]; then
          echo "TAGS=agente11/github-actions:latest,agente11/github-actions:${{ inputs.version }}" >> $GITHUB_ENV
        else
          echo "TAGS=agente11/github-actions:${{ inputs.version }}" >> $GITHUB_ENV
        fi

    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Create new builder
      run: docker buildx create --use

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        tags: ${{ env.TAGS }}
